console.log("Hello World");
        let a = 10;
        console.log(a);
        console.log(typeof(a));
        a=false;
        console.log(a);
        console.log(typeof(a));
        a="Hello World";
        console.log(a);
        console.log(typeof(a));
        a=null;
        console.log(a);
        console.log(typeof(a));